[build]
functions = "functions"

[[redirects]]
from = "/search"
to = "/index.html"
status = 200

[[redirects]]
from = "/analyse"
to = "/index.html"
status = 200

[[redirects]]
from = "/preferences"
to = "/index.html"
status = 200

[[redirects]]
from = "/newest/*"
to = "https://thisvid.com/newest/:splat"
status = 200

[[redirects]]
from = "/new-private/*"
to = "https://thisvid.com/new-private/:splat"
status = 200

[[redirects]]
from = "/gay-newest/*"
to = "https://thisvid.com/gay-newest/:splat"
status = 200

[[redirects]]
from = "/gay-private/*"
to = "https://thisvid.com/gay-private/:splat"
status = 200

[[redirects]]
from = "/members/*"
to = "https://thisvid.com/members/:splat"
status = 200

[[redirects]]
from = "/videos/*"
to = "https://thisvid.com/videos/:splat"
status = 200

[[redirects]]
from = "/categories/*"
to = "https://thisvid.com/categories/:splat"
status = 200

[[redirects]]
from = "/tags/*"
to = "https://thisvid.com/tags/:splat"
status = 200

[[redirects]]
from = "/female-extreme/*"
to = "https://thisvid.com/female-extreme/:splat"
status = 200

[[redirects]]
from = "/male-extreme/*"
to = "https://thisvid.com/male-extreme/:splat"
status = 200

[[redirects]]
from = "/getVideos"
to = "https://tvass.netlify.app/.netlify/functions/videos"
status = 200

[[redirects]]
from = "/download"
to = "https://tvass.netlify.app/.netlify/functions/download"
status = 200

[[redirects]]
from = "/friends"
to = "https://tvass.netlify.app/.netlify/functions/friends"
status = 200

[[redirects]]
from = "/feed"
to = "https://tvass.netlify.app/.netlify/functions/feed"
status = 200

